language: php
php:
  - '7.1'

install:
  - composer install
  - cp .env.example .env
  - php artisan key:generate

services:
  - mongodb
  - redis-server

addons:
  ssh_known_hosts:
    - sir-edgar.com

env:
  global:
    - APP_ENV=testing

before_install:
  - pecl -q install mongodb && echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

addons:
  ssh_known_hosts:
    - sir-edgar.com

deploy:
  - provider: script
      skip_cleanup: true
      script: envoy run deploy
      on:
        branch: master