language: php
php:
  - '7.1'

install:
  - composer install

services:
  - mongodb

env:
  global:
    - DB_CONNECTION=mongodb
    - DB_HOST=127.0.0.1
    - DB_PORT=27017
    - APP_ENV=testing

before_install:
  - pecl -q install mongodb && echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

before_script:
  - php artisan key:generate