language: php
php:
  - '7.1'

branches:
  only:
    - master
    - develop
    - feature/test-travis

install:
  - composer install
  - cp .env.example .env
  - php artisan key:generate

services:
  - mongodb
  - redis-server

addons:
  ssh_known_hosts: sir-edgar.com

env:
  global:
    - APP_ENV=testing

before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
  - sudo apt-get update
  - sudo apt-get install -y php7.1-fpm php7.1-mysql php7.1-curl php7.1-gd php7.1-json php7.1-mcrypt php7.1-opcache php7.1-xml php7.1-mbstring php7.1-dev php7.1-intl php7.1-zip php7.1-gd php7.1-mongodb unzip mongodb

before_deploy:
  - openssl aes-256-cbc -K $encrypted_e1ea4e0d88f8_key -iv $encrypted_e1ea4e0d88f8_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - export PATH="/home/travis/.composer/vendor/bin:$PATH"
  - composer global require laravel/envoy

after_deploy:
  - rm deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: envoy run deploy
    on:
      branch:
        - master
        - develop