language: php
php:
  - '7.1'

install:
  - composer install
  - cp .env.example .env
  - php artisan key:generate

services:
  - mongodb
  - redis-server

env:
  global:
    - APP_ENV=testing

before_install:
  - pecl -q install mongodb && echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`