language: php
php:
  - '7.1'

install:
  - composer install
  - cp .env.example .env
  - php artisan key:generate

services:
  - mongodb
  - redis-server

addons:
  ssh_known_hosts:
    - sir-edgar.com

env:
  global:
    - APP_ENV=testing

before_install:
  - pecl -q install mongodb && echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

addons:
  ssh_known_hosts:
    - sir-edgar.com

before_deploy:
  - openssl aes-256-cbc -K $encrypted_e1ea4e0d88f8_key -iv $encrypted_e1ea4e0d88f8_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - rm deploy_rsa

deploy:
  - provider: script
    script: envoy run deploy
    on:
      branch:
        - master
        - deploy